### ISSUE TITLE
Life Q30(A3028)/Life Tune (A3029) Support

### ISSUE THREAD

**Issue by gmallios** [gmallios/SoundcoreManager#9]
Life Q30 (A3028) is working perfectly, but the custom ANC setting and the "vocal mode" in the transparency mode isn't supported by the headset.
Also, we can safely say that the Life Tune (A3029) works as well as it is a Q30 (A3028) with a logo change.
https://fccid.io/2AOKB-A3028/Attestation-Statements/Family-declaration-4855135

_Originally posted by @Maxcension in https://github.com/gmallios/SoundcoreManager/issues/1#issuecomment-1417704439_

**Comment by gmallios** [comment]
@Maxcension I assume from your answer that EQ works, is that right?

**Comment by Maxcension** [comment]
> @Maxcension I assume from your answer that EQ works, is that right?

Yup! And the changes are perfectly saved in the headset.
If you need me to do or test anything, don't hesitate to ask me!

**Comment by gmallios** [comment]
@Maxcension Please test out the new build found in the README and let me know how it works out!

**Comment by Maxcension** [comment]
@gmallios Hey! The EQ works but there is no ANC anymore :( 

New build:
![image](https://user-images.githubusercontent.com/10364593/219955789-31027260-e9fb-4e84-9969-5e4e65103aeb.png)
Old build:
![image](https://user-images.githubusercontent.com/10364593/219955768-6ba7a44e-f307-4a50-b8e7-aa001f6aa989.png)

**Comment by gmallios** [comment]
Sorry about that! I've pushed a new commit to fix it, it should be done building in 10 mins.

**Comment by Maxcension** [comment]
> Sorry about that! I've pushed a new commit to fix it, it should be done building in 10 mins.

I'll test it :)

Btw, it's a detail but the image used for the headset has a thin white pixelated outline, why not using this one: 
![blue](https://user-images.githubusercontent.com/10364593/219956873-7a15bffd-ed8e-4afe-a1f0-2d070559644b.png)
Or this one:
![black](https://user-images.githubusercontent.com/10364593/219956877-de4f2bf4-c950-4bff-9bfc-c6c137458494.png)

**Comment by gmallios** [comment]
I can use those for sure! I exctract the images straight from the official Soundcore app but those look better. Thank you!

**Comment by igorbmaciel** [comment]
Hello guys, how are you?
I'm trying to connect with my Q30, but after click in connect it's loading forever. I need to install more things?

**Comment by GabryDX** [comment]
I'm experiencing connection problems on this device

![image](https://user-images.githubusercontent.com/6898706/234872084-94255bf8-335b-4380-a1e3-cfd9cf6faf5d.png)

It is recognized here but then it jsut keeps loading, and in console there are no errors and just this connection message:

![image](https://user-images.githubusercontent.com/6898706/234872438-8042301c-3242-4317-9ea9-5794deb14f4a.png)

I'm using the latest build at the moment. Thanks for the project and thanks in advance for the help.

**Comment by gmallios** [comment]
> I'm experiencing connection problems on this device
> 
> ![image](https://user-images.githubusercontent.com/6898706/234872084-94255bf8-335b-4380-a1e3-cfd9cf6faf5d.png)
> 
> It is recognized here but then it jsut keeps loading, and in console there are no errors and just this connection message:
> 
> ![image](https://user-images.githubusercontent.com/6898706/234872438-8042301c-3242-4317-9ea9-5794deb14f4a.png)
> 
> I'm using the latest build at the moment. Thanks for the project and thanks in advance for the help.



Sorry to hear that, could you try an older build ([this one](https://github.com/gmallios/SoundcoreManager/actions/runs/4644924982))? You can find the file at the bottom of the page.
![image](https://user-images.githubusercontent.com/44323649/234976029-fa1fae46-4723-4fc0-a515-3c3e18ee265b.png)

**Comment by GabryDX** [comment]
Hi, thanks for the response. Yes, this older version loads instantly.

**Comment by gmallios** [comment]
@GabryDX Can you try the latest build? I want to know if the fix i pushed worked for other devices.

**Comment by GabryDX** [comment]
Hi, it is still not working. I can leave you here what I can see in the log file:

```
[2023-04-30][16:09:57][soundcoremanager::tray][DEBUG] Setting tray menu to connected status: false
[2023-04-30][16:09:59][bluetooth_lib::winrt::rfcomm][TRACE] Connecting to E8:EE:CC:46:4D:AB with uuid 00001101-0000-1000-8000-00805F9B34FB
[2023-04-30][16:10:12][tao::platform_impl::platform::event_loop::runner][WARN] NewEvents emitted without explicit RedrawEventsCleared
[2023-04-30][16:10:12][tao::platform_impl::platform::event_loop::runner][WARN] RedrawEventsCleared emitted without explicit MainEventsCleared
```

I don't know if the warning is linked to me opening the console, but anyway this is what I have, thank you for your patience.

**Comment by gmallios** [comment]
> Hi, it is still not working. I can leave you here what I can see in the log file:
> 
> ```
> [2023-04-30][16:09:57][soundcoremanager::tray][DEBUG] Setting tray menu to connected status: false
> [2023-04-30][16:09:59][bluetooth_lib::winrt::rfcomm][TRACE] Connecting to E8:EE:CC:46:4D:AB with uuid 00001101-0000-1000-8000-00805F9B34FB
> [2023-04-30][16:10:12][tao::platform_impl::platform::event_loop::runner][WARN] NewEvents emitted without explicit RedrawEventsCleared
> [2023-04-30][16:10:12][tao::platform_impl::platform::event_loop::runner][WARN] RedrawEventsCleared emitted without explicit MainEventsCleared
> ```
> 
> I don't know if the warning is linked to me opening the console, but anyway this is what I have, thank you for your patience.

Hmm, the warnings are unrelated and expected. I have pushed a new build with more verbose logging to see what's going on with the new Bluetooth API. What Windows version are you running? ,The WinRT SDK works for versions after Windows 10 build 10240.

**Comment by GabryDX** [comment]
Hi, I've tried the latest version and here are the logs:

```
[2023-05-02][22:15:23][soundcoremanager::tray][DEBUG] Setting tray menu to connected status: false
[2023-05-02][22:15:23][soundcoremanager::device][DEBUG] Closing device
[2023-05-02][22:15:24][bluetooth_lib::win32::scanner][DEBUG] Found 3 devices using win32 bt scan
[2023-05-02][22:15:26][bluetooth_lib::winrt::rfcomm][TRACE] Connecting to E8:EE:CC:46:4D:AB with uuid 00001101-0000-1000-8000-00805F9B34FB
```

My Windows 10 build is 19045.2846.

Thanks.

**Comment by gmallios** [comment]
@GabryDX I added some additional logs in the latest build, i can't replicate this on multiple Windows machines i own 😢

**Comment by GabryDX** [comment]
I have just tried the latest version and now it works. Just to be sure I have checked the previous one and that still does not work, so I think you really fixed that in this release, thanks! 😄

**Comment by gmallios** [comment]
Hmm, perfect! Windows APIs are magic 😆
